db/migration/V5_0__create_combined_patient_table.sql
minimart-manager/local-mitre-db.sh
minimart-manager/pom.xml
minimart-manager/src/test/java/gov/va/api/health/minimartmanager/DatamartExporter.java
minimart-manager/src/test/java/gov/va/api/health/minimartmanager/minimart/MitreMinimartMaker.java

New Patient table loaded with synthetic data

new patient table loaded with records

---

db/migration/V5_2__alter_observation_dateutc.sql
minimart-manager/pom.xml

https://vajira.max.gov/browse/API-248

API-248 Alter Observation dateUtc column to smalldatetime

---

db/migration/V5_2__alter_observation_dateutc.sql
minimart-manager/pom.xml
minimart-manager/src/test/java/gov/va/api/health/minimartmanager/minimart/MitreMinimartMaker.java
minimart-manager/src/test/java/gov/va/api/health/minimartmanager/minimart/transformers/F2DPatientTransformer.java

https://github.com/department-of-veterans-affairs/lighthouse-maintenance/pull/144

staging_lab to lab

---

datamart/dm-records-1017283180V801730/dmOrg457959I.json
datamart/dm-records-1017283180V801730/dmOrg561596I.json
datamart/dm-records-1017283180V801730/dmOrg568060I.json

https://vajira.max.gov/browse/API-1717

API-1717-synth-organizations

---

datamart/dm-records-1017283180V801730/dmLoc43817L.json
datamart/dm-records-1017283180V801730/dmLoc43829L.json
datamart/dm-records-1017283180V801730/dmLoc43841L.json

References the following Organization Records:
datamart/dm-records-1017283180V801730/
- dmOrg457959I.json
- dmOrg561596I.json
- dmOrg568060I.json

API-1721-synth-locations

---

datamart/dm-records-43000199/dmDev800001608620.json
datamart/dm-records-43000199/dmDev800001608621.json
db/migration/V7_0__create_device.sql
minimart-manager/local-mitre-db.sh
minimart-manager/pom.xml
minimart-manager/src/test/java/gov/va/api/health/minimartmanager/DatamartExporter.java
minimart-manager/src/test/java/gov/va/api/health/minimartmanager/PopulateDb.java
minimart-manager/src/test/java/gov/va/api/health/minimartmanager/minimart/DatamartFilenamePatterns.java
minimart-manager/src/test/java/gov/va/api/health/minimartmanager/minimart/MitreMinimartMaker.java

Api 3434 add device records

---

db/migration/V7_1__create_device_primary_key.sql

Fixes problem where Device record updates get stuck when trying to commit to the database.

API-3434-update-problems

---

db/migration/V7_1__create_device_primary_key.sql

https://github.com/department-of-veterans-affairs/lighthouse-devops-support/issues/50

MR 50 (#77)

---

db/migration/V9_0__add_patient_columns_ssn_npi.sql

API-4127-add-new-columns

---

minimart-manager/pom.xml
minimart-manager/src/test/java/gov/va/api/health/minimartmanager/minimart/MitreMinimartMaker.java

API-4129-populate-ssn

---

db/migration/V12_3__alter_appointment.sql

fix appointment type to appointment code

---

minimart-manager/pom.xml
minimart-manager/src/test/java/gov/va/api/health/minimartmanager/minimart/MitreMinimartMaker.java

API-2563-locationsid-int

---

datamart/db-dumps/VistaVuidVitalsMapping.csv
minimart-manager/local-mitre-db.sh
minimart-manager/pom.xml
minimart-manager/src/test/java/gov/va/api/health/minimartmanager/DatamartExporter.java
minimart-manager/src/test/java/gov/va/api/health/minimartmanager/PopulateDb.java
minimart-manager/src/test/java/gov/va/api/health/minimartmanager/minimart/CsvDataFile.java
minimart-manager/src/test/java/gov/va/api/health/minimartmanager/minimart/MitreMinimartMaker.java

~Waiting on https://github.com/department-of-veterans-affairs/health-apis-vista-fhir-query/pull/21~

API-5144-populate-db

---

datamart/dm-records-1017283180V801730/dmLoc43829L.json
datamart/dm-records-1017283180V801730/dmLoc43841L.json
datamart/dm-records-1017283180V801730/dmOrg561596I.json
datamart/dm-records-1017283180V801730/dmOrg568060I.json
minimart-manager/pom.xml

Requires [DQ update](https://github.com/department-of-veterans-affairs/health-apis-data-query/pull/679)

API-5660 populate facilityId and locationIen for location

---

minimart-manager/src/test/java/gov/va/api/health/minimartmanager/minimart/MitreMinimartMaker.java

API-000-populate-observation-date

---

db/migration/V14_0__refactor_organization.sql

https://lighthouseva.slack.com/archives/C01DABTTQDA/p1613575645168400?thread_ts=1613411404.152000&cid=C01DABTTQDA

API-6140-update-org-table

---

minimart-manager/pom.xml
minimart-manager/src/test/java/gov/va/api/health/minimartmanager/minimart/MitreMinimartMaker.java

API-6142-load-facility-id

---

db/migration/V15_0__alter_location.sql

* Added Location columns: StationNumber, FacilityType, and LocationIEN

API 4877 New Location Migration (#117)

---

db/migration/V15_0__alter_location.sql
minimart-manager/pom.xml
minimart-manager/src/test/java/gov/va/api/health/minimartmanager/minimart/MitreMinimartMaker.java

Populate the new Location columns.

API 4877 Location Identifier Update

---

run-local.sh

API-000-fix-docker-user

---

db/migration/V15_1__alter_location.sql

Updated Location schema to include Managing Organization.
@nmoisan @jtaylor-va @haidong pinging as requested.

API 6503 Location Organization Search

---

datamart/dm-records-1017283180V801730/dmPraRol294582.json
datamart/dm-records-1017283180V801730/dmPraRol305693.json
datamart/dm-records-1017283180V801730/dmPraRol416704.json
minimart-manager/pom.xml
minimart-manager/src/test/java/gov/va/api/health/minimartmanager/minimart/MitreMinimartMaker.java

Adds `active` and `telecom` fields to PractitionerRole payloads to be consistent with CDW.

API-7561: PractitionerRole: add active and telecom

---

db/migration/V17_4__alter_practitioner.sql
db/migration/V17_5__create_practitioner_role_specialty_map.sql
minimart-manager/local-mitre-db.sh
minimart-manager/pom.xml
minimart-manager/src/test/java/gov/va/api/health/minimartmanager/DatamartExporter.java
minimart-manager/src/test/java/gov/va/api/health/minimartmanager/PopulateDb.java
minimart-manager/src/test/java/gov/va/api/health/minimartmanager/minimart/MitreMinimartMaker.java

1. fixes PK on `Practitioner`
2. Adds `PractitionerRole_Specialty_Map` entity, consistent with CDW schema
3. Updates minimart-maker to re-index specialty mappings for each PractitionerRole file.

API-8342: PractitionerRole Specialty Mapping

---

db/migration/V17_6__alter_practitioner.sql
minimart-manager/pom.xml
minimart-manager/src/test/java/gov/va/api/health/minimartmanager/minimart/MitreMinimartMaker.java

see [data-query](https://github.com/department-of-veterans-affairs/health-apis-data-query/pull/768)

API-8573 remove Practitioner cdwId

---

minimart-manager/pom.xml
minimart-manager/src/test/java/gov/va/api/health/minimartmanager/minimart/augments/AllergyIntoleranceClinicalAndVerificationStatusAugments.java

https://vajira.max.gov/browse/API-9760
109 `dmAllInt*` files will be impacted

API-9760 augment for allergy-intolerance clinical and verification status
